Test rollback document suggested modification
grails/grails-doc pull request #699
Opened 2019-02-13 08:25 UTC by wxw310415

2019-02-13 08:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grails/grails-doc?pullRequest=699) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grails/grails-doc?pullRequest=699) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grails/grails-doc?pullRequest=699) it.</sub>

2019-04-18 19:28 UTC, niravassar commented on src/en/guide/testing/integrationTesting.adoc
> +In Grails 3.0 tests rely on `grails.transaction.Rollback` annotation to bind the session in integration tests. Though each test method transaction is rolled back, the `setup()` method uses a separate
I think this `... is not rolled back and the setup()...` should be broken into a sentence like this:

 `is not rolled back. The setup() `

2019-04-18 19:29 UTC, niravassar commented on src/en/guide/testing/integrationTesting.adoc
> +        // Do not use this method
These two lines should not be commented out in the example, and the comment should be
`// This line will not roll back`

2019-04-18 19:29 UTC, niravassar requested changes
Let me know what you think of these changes and we can merge it as i like the idea

2024-11-11 21:55 UTC, jamesfredley commented
closed due to age

2024-11-11 21:55 UTC, closed without merging